### ISSUE TITLE
`log-ignore-test-fixture` is not ignoring logs

### ISSUE THREAD

**Issue by dfrese** [active-group/active-logger#10]
The `test/log-ignore-test-fixture` sets the config to `(make-timbre-config {})`, which in turn uses the base/example appenders, which include a println-appender:

https://github.com/active-group/active-logger/blob/main/src/active/clojure/logger/timbre.clj#L46

I think using ´(make-timbre-config {:appenders []})` should fix this.

**Comment by cresh** [comment]
I've fixed this. Do you need a new release?
